export const countries = [
    "Abecácia", "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Argélia", "Andorra", "Angola",
    "Anguila", "Antígua e Barbuda", "Argentina", "Armênia", "Aruba",
    "Austrália", "Áustria", "Azerbaijão", "Bahamas", "Bahrein", "Bangladesh",
    "Barbados", "Bielorrússia", "Bélgica", "Belize", "Benin", "Bermuda", "Butão",
    "Bolívia", "Bósnia e Herzegovina", "Botsuana", "Brasil", "Ilhas Virgens Britânicas",
    "Brunei", "Bulgária", "Burkina Faso", "Burundi", "Camboja", "Camarões", "Cabo Verde",
    "Ilhas Cayman", "Chade", "Chile", "China", "Colômbia", "Congo", "Ilhas Cook", "Costa Rica",
    "Cote D Ivoire", "Croácia", "Navio de Cruzeiro", "Cuba", "Chipre", "República Tcheca", "Dinamarca",
    "Djibuti", "Dominica", "República Dominicana", "Equador", "Egito", "El Salvador", "Guiné Equatorial",
    "Estônia", "Etiópia", "Ilhas Malvinas", "Ilhas Faroé", "Fiji", "Finlândia",
    "França", "Polinésia Francesa", "Índias Ocidentais Francesas", "Gabão", "Gâmbia", "Geórgia",
    "Alemanha", "Gana", "Gibraltar", "Grécia", "Gronelândia", "Granada", "Guam",
    "Guatemala", "Guernsey", "Guiné", "Guiné Bissau", "Guiana", "Haiti", "Honduras",
    "Hong Kong", "Hungria", "Islândia", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda",
    "Ilha de Man", "Israel", "Itália", "Jamaica", "Japão", "Jersey", "Jordânia",
    "Cazaquistão", "Quênia", "Kuwait", "República do Quirguistão", "Laos", "Letônia", "Líbano",
    "Lesoto", "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo", "Macau",
    "Macedônia", "Madagascar", "Malawi", "Malásia", "Maldivas", "Mali", "Malta",
    "Mauritânia", "Maurícia", "México", "Moldávia", "Mônaco", "Mongólia", "Montenegro",
    "Montserrat", "Marrocos", "Moçambique", "Namíbia", "Nepal", "Holanda",
    "Antilhas Holandesas", "Nova Caledônia", "Nova Zelândia", "Nicarágua", "Níger",
    "Nigéria", "Noruega", "Omã", "Paquistão", "Palestina", "Panamá", "Papua Nova Guiné",
    "Paraguai", "Peru", "Filipinas", "Polônia", "Portugal", "Porto Rico", "Catar",
    "Reunião", "Roménia", "Rússia", "Ruanda", "Saint Pierre &amp; Miquelon", "Samoa",
    "San Marino", "Satélite", "Arábia Saudita", "Senegal", "Sérvia", "Seychelles",
    "Serra Leoa", "Singapura", "Eslováquia", "Eslovênia", "África do Sul", "Coreia do Sul",
    "Espanha", "Sri Lanka", "São Cristóvão e Nevis", "Santa Lúcia", "São Vicente",
    "Santa Lúcia", "Sudão", "Suriname", "Suazilândia", "Suécia", "Suíça", "Síria",
    "Taiwan", "Tajiquistão", "Tanzânia", "Tailândia", "Timor L'Este", "Togo", "Tonga",
    "Trinidad e Tobago", "Tunísia", "Turquia", "Turquemenistão", "Turks e Caicos",
    "Uganda", "Ucrânia", "Emirados Árabes Unidos", "Reino Unido", "Uruguai",
    "Uzbequistão", "Venezuela", "Vietnã", "Ilhas Virgens (EUA)", "Iêmen", "Zâmbia",
    "Zimbábue"
];